name: Deploy to Firebase on merge
'on':
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13.7.1

      - name: Write credentials, environment variables and secrets to files
        env: 
          BOT_ENDPOINT: ${{ secrets.BOT_ENDPOINT }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WHATSAPP_LINK_GENERATOR_4AA16 }}
        working-directory: ./functions
        run: |
          echo "BOT_ENDPOINT=$BOT_ENDPOINT" >> .env
          echo "BOT_TOKEN=$BOT_TOKEN" >> .env
          echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > credentials.json

      - name: Deploy Firebase Functions
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: ./functions/credentials.json
        run: firebase deploy --project "${{ vars.FIREBASE_PROJECT_ID }}"
