name: Deploy to Firebase on merge
'on':
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - run: npm ci
        working-directory: ./functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13.7.1

      - name: Write credentials to file
        env: 
          GOOGLE_APPLICATION_CREDENTIALS_JSON: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_WHATSAPP_LINK_GENERATOR_4AA16 }}'
        run: 'echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > credentials.json'

      - name: Deploy Firebase Functions
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: ./credentials.json
        run: firebase deploy --debug --project "${{ vars.FIREBASE_PROJECT_ID }}"
